name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read        # Needed to read repository
  pages: write          # Needed to deploy to GitHub Pages
  id-token: write       # Needed for GitHub Pages environment

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. Upload site files (everything in repo root)
      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # Make sure all files (index.html, CSS, JS, images) are in repo root

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
